### PR TITLE
PDAL 2.7.x

### PR DESCRIPTION
**Pull request by pomadchin**
Closes https://github.com/PDAL/java/issues/93

### CODE REVIEW

**Comment by WhiteSte** [comment]
Hi, the publish job of this PR has been skipped by the runner. Was this intentional?

**Comment by pomadchin** [comment]
Hi @WhiteSte, yes. Its published only by merge into the main branch, see https://github.com/PDAL/java/actions/runs/8348027136/job/22849514570

**Comment by WhiteSte** [comment]
i do not see it in maven central, does it takes some time after the pipeline finishes?

**Comment by pomadchin** [comment]
It is released as a snapshot: https://oss.sonatype.org/content/repositories/snapshots/io/pdal/pdal_2.13/2.6.3+1-a017f86c-SNAPSHOT/ 

I haven't clicked the button to do the 2.7.0 release.

**Comment by WhiteSte** [comment]
I see, thanks

**Pull request merged**
